name: ethereum_codec
version: 0.1.0

dependencies:
  convert: ^2.1.1
  pointycastle: ^1.0.1
  typed_data: ^1.2.0
  ethereum_util:
    git:
      url: https://github.com/GreenAppers/ethereum_util
  eth_abi_codec:
    git:
      url: https://github.com/nbltrust/dart-eth-abi-codec

environment:
  sdk: ">=1.19.0 <3.0.0"